src/fifa.league.web/Controllers/MatchReportController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace fifa.league.web.Controllers
{
    public class MatchReportController : Controller
    {
        //
        // GET: /MatchReport/
        public ActionResult Index()
        {
            return View();
        }
	}
}

src/fifa.league.web/Controllers/UserController.cs
using System.Collections.Generic;
using System.Linq;
using System.Net;
using System.Net.Http;
using System.Web.Mvc;
using fifa.league.web.Models;
using MongoDB.Bson;
using MongoDB.Driver;
using Newtonsoft.Json;

namespace fifa.league.web.Controllers.api
{
    public class UserController : Controller
    {
        private MongoClient _client;
        private MongoServer _server;
        private MongoDatabase _db;

        public UserController()
        {
             _client = new MongoClient("mongodb://rthapa:rthapa@ds036648.mongolab.com:36648/fifaleague");
            _server = _client.GetServer();
            _db = _server.GetDatabase("fifaleague");
        }
        public ActionResult Index()
        {
            return View();
        }
    }
}

src/fifa.league.web/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html ng-app="myApp" class="ng-cloak">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width" />
    <title>@ViewBag.Title</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Home", "Index", "Home", null, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Add New Match", "Index", "MatchReport", new { area = "" }, null)</li>
                    <li>@Html.ActionLink("Add player", "Index", "User", new { area = "" }, null)</li>
                    <li>@Html.ActionLink("History", "Index", "History", new { area = "" }, null)</li>
                </ul>
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - My ASP.NET Application</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    <script src="../../Scripts/angular.js"></script>
    <script src="../../Scripts/models/app.js"></script>
    <script src="../../Scripts/models/league.js"></script>
    <script src="../../Scripts/models/matchReport.js"></script>
    <script src="../../Scripts/models/user.js"></script>
    <script src="../../Scripts/models/history.js"></script>
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>